### ISSUE TITLE
Open a gist with the API information

### ISSUE THREAD

**Issue by iWexter** [garygreen/arrow-table#2]
I like to learn more about all internal commands with more examples

**Comment by garygreen** [comment]
It's a pretty simple plugin. What do you need to know specifically?

**Comment by iWexter** [comment]
Exists any command to know the first and last column?
How to call a direction from outside the plugin code like 
```javascript
$('#table').arrowTable({
   beforeMove: function(input, targetFinder, direction) {
      if (direction === 'right') {
         //Move to certain direction
      }
   }
});
```
This is necessary for me because when I filled the last one column, the expectation is that focus the first column of next line using right arrow.

So... I want to know more about the plugin to modify it in case doesn't exist

**Comment by garygreen** [comment]
That would definitely be a nice addition, essentially a "wrap" feature that wraps to the next column / row when moving in that direction, if nesscary.

At the moment it's not easily possible. You would have to implement your own logic in `beforeMove` and `return false` to prevent the default movement.

This plugin was created quite a while ago and I do have ideas on how to improve it, one thing else I'd like to do is remove the need for jQuery.

**Comment by iWexter** [comment]
It's a great idea don't use jQuery, maybe will be nice transform to EC6 although I'm not a really good I can try to make the transformation, but thank you for the answers
